### 회원가입
POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "id": "test1",
  "email": "test1@test.com",
  "password": "1234",
  "nickname": "테스트유저",
  "age": 24,
  "gender": "남자",
  "height": 170.0,
  "weight": 70.0,
  "desease": ["DIABETES", "HYPERTENSION"]
}

### 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "id": "test1",
  "password": "1234"
}

### 음식 분석
POST http://localhost:8080/api/meals/analyze?userId=test1
Content-Type: application/json

{
  "detectedFoods": [
    {
      "food_name": "김치찌개",
      "nutrient_name": {
        "kcal": 350,
        "carbs": 20,
        "protein": 18,
        "fat": 22,
        "sugar": 5,
        "sodium": 1200,
        "cholesterol": 40,
        "kalium": 500,
        "phos": 200
      }
    }
  ]
}


### 여러 음식 분석 테스트
POST http://localhost:8080/api/meals/analyze?userId=test1
Content-Type: application/json

{
  "detectedFoods": [
    {
      "food_name": "김치찌개",
      "nutrient_name": {
        "kcal": 350,
        "carbs": 20,
        "protein": 18,
        "fat": 22,
        "sugar": 5,
        "sodium": 1200,
        "cholesterol": 40,
        "kalium": 500,
        "phos": 200
      }
    },
    {
      "food_name": "삶은 계란",
      "nutrient_name": {
        "kcal": 80,
        "carbs": 1,
        "protein": 7,
        "fat": 5,
        "sugar": 0,
        "sodium": 60,
        "cholesterol": 180,
        "kalium": 70,
        "phos": 90
      }
    }
  ]
}