spring.application.name=capstone2026

# DB ?? ?? (? ?? capstone_db? ?????? ?? ??? ??? ?)
spring.datasource.url=jdbc:mysql://localhost:3306/capstone_db?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=root

# JPA ??
# update: ?? ??? ??? ???? DB ??? ??? ???? ?????.
spring.jpa.hibernate.ddl-auto=update
# ?? ?? ? ?? SQL? ????? ??? ??? ?????.
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true